# Generated by Django 5.0.6 on 2024-05-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
