# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=lp123456
    ports: 
      - '3309:3306'
     

    # (this is just an example, not intended to be a production configuration)